version: 7.5.2.{Build}
branches:
  only:
  - csharp
build_script:
- cmd: .\build.bat
test: off
artifacts:
- path: ./build/PhoneNumbers.dll
  name: PhoneNumbers (unsigned)
- path: ./build/signed/PhoneNumbers.dll
  name: PhoneNumbers (signed)
- path: /version.txt
  name: Version