// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("PhoneNumbers")]
[assembly: AssemblyDescriptionAttribute("Google's libphonenumber")]
[assembly: AssemblyProductAttribute("PhoneNumbers")]
[assembly: AssemblyCopyrightAttribute("Copyright © Google 2015")]
[assembly: AssemblyVersionAttribute("7.4.1")]
[assembly: AssemblyFileVersionAttribute("7.4.1")]
[assembly: AssemblyKeyFileAttribute("key.snk")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "7.4.1";
    }
}
