// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("PhoneNumbers")]
[assembly: AssemblyDescriptionAttribute("Google's libphonenumber")]
[assembly: AssemblyProductAttribute("PhoneNumbers")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2015-2016 Google")]
[assembly: AssemblyVersionAttribute("7.4.6.0")]
[assembly: AssemblyFileVersionAttribute("7.4.6.0")]
[assembly: AssemblyKeyFileAttribute("key.snk")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "7.4.6.0";
    }
}
